//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.03 at 05:59:50 PM CEST 
//


package com.sun.jersey.json.impl.rim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Models the familiar “PostIt attached to papers” metaphor.
 *         Used to attach comments to Register during registration procedures, may be used to comment on any RegistryObject.
 *         Implemented as a sub-type of ExtrinsicObjectType.
 *         If comment is small it is specified in description field.
 *         If comment is large or needs formatting, images etc. then it is specified in the RepositoryItem as a document.
 *         Adding a comment to a RegistryObject done by defining a “HasComment” Association with an ExtrinsicObject with objectType “Comment”.
 *       
 * 
 * <p>Java class for CommentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommentType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0}ExtrinsicObjectType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommentType")
public class CommentType
    extends ExtrinsicObjectType
{


}
