//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.03 at 05:59:50 PM CEST 
//


package com.sun.jersey.json.impl.rim;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Represents a collection of objects that is governed by a shared set of policies and managed by a designated 
 *         set of steward organizations where each organization has specific stewardship roles.
 *       
 * 
 * <p>Java class for RegisterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0}RegistryPackageType">
 *       &lt;attribute name="registerOwner" use="required" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0}objectReferenceType" />
 *       &lt;attribute name="registerManager" use="required" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0}objectReferenceType" />
 *       &lt;attribute name="controlBody" use="required" type="{urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0}objectReferenceType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterType")
public class RegisterType
    extends RegistryPackageType
{

    @XmlAttribute(required = true)
    protected String registerOwner;
    @XmlAttribute(required = true)
    protected String registerManager;
    @XmlAttribute(required = true)
    protected String controlBody;

    /**
     * Gets the value of the registerOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterOwner() {
        return registerOwner;
    }

    /**
     * Sets the value of the registerOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterOwner(String value) {
        this.registerOwner = value;
    }

    /**
     * Gets the value of the registerManager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisterManager() {
        return registerManager;
    }

    /**
     * Sets the value of the registerManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisterManager(String value) {
        this.registerManager = value;
    }

    /**
     * Gets the value of the controlBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getControlBody() {
        return controlBody;
    }

    /**
     * Sets the value of the controlBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setControlBody(String value) {
        this.controlBody = value;
    }

}
