package com.sun.jersey.samples.helloworld.resources


import _root_.java.util.Date
import javax.ws.rs.{Produces, GET, Path}

/**
 * A resource bean which uses Scala markup to generate the response , to be used with jersey-scala library
 *
 * @version $Revision: 1.1 $
 */
@Path("markup")
class MarkupResource {
  val name = "James"

  @Produces(Array("text/html"))
  @GET
  def get() = <html>
    <body>
    <h1>Hello {name}</h1>
    <p>Markup generated by Scala code at {new Date()}</p>
    </body>
  </html>
}